# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: "Update Helm Docs"

on:
  push:

jobs:
  helm-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_COMMITS_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_COMMITS_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Download Helm Docs
        run: |
          mkdir helm-docs
          cd helm-docs

          curl --output helm-docs.tar.gz --location https://github.com/norwoodj/helm-docs/releases/download/v1.5.0/helm-docs_1.5.0_Linux_x86_64.tar.gz
          tar -xvf helm-docs.tar.gz
          # Verify installation
          ./helm-docs --version

      - name: Generate Helm Docs
        run: |
          ./helm-docs/helm-docs --template-files=./_templates.gotmpl --template-files=README.md.gotmpl --output-file=README.md
      - name: Generate Docker Scanner Docs
        run: |
          ./helm-docs/helm-docs --chart-search-root=./scanners/ --template-files=./../_templates.gotmpl --template-files=README.templates.gotmpl --template-files=README.DockerHub-Scanner.md.gotmpl --output-file=docs/README.DockerHub-Scanner.md
      - name: Remove Helm Docs Files
        run: |
          # Remove helm-docs download to ensure they don't get commited back
          rm -rf helm-docs
      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Updating Helm Docs
          commit_user_email: securecodebox@iteratec.com
